# fly.toml app configuration file generated for educa-facil

app = "educa-facil"
primary_region = "gru"  # São Paulo region

[build]

[env]
  FLASK_ENV = "production"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
