services:
  - type: web
    name: escola-para-todos
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /
    autoDeploy: true
